[book]
authors = ["sherif-ibn-nasser"]
language = "ar"
multilingual = false
src = "src"
title = "لغة نظم"


[build]
build-dir = "../docs"

[output.html]
additional-css = ["css/language-nazm.css"]
additional-js = [
    "highlight.js",
    "book.js",
    "js/xregexp-all.js",
    "js/highlight.min.js",
    "js/nazm.js",
    "js/book.js",
    "js/change-titles.js",
]

[output.html.print]
enable = false

[output.html.search]
enable = false
